name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  drive:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/chekout@v3

      - name: Install dependencies
        run: python -m pip install pytest .

      - name: Run test
        run: pytest
