name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    name: Test
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/chekout@v3

      - name: Set up Python
        uses: action/setup-python@v4

      - name: Install dependencies
        run: python -m pip install pytest .

      - name: Run test
        run: pytest
